### ISSUE TITLE
Production deployment has dependencies on specific test data

### ISSUE THREAD

**Issue by matt9j** [uw-ictd/commgestion-web#34]
Running the site in production fails with the following error:
```
Environment:


Request Method: GET
Request URL: http://prothean.cs.washington.edu/

Django Version: 3.0.4
Python Version: 3.7.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'web']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/var/commgestion/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/commgestion/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/commgestion/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/commgestion/web/views.py", line 23, in public_info
    gauge = public_view.generate_test_data()
  File "/var/commgestion/web/public_view.py", line 15, in generate_test_data
    usr = Subscriber.objects.get(phonenumber='123456789' + str(random.randint(0, 4)))
  File "/var/commgestion/.venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/commgestion/.venv/lib/python3.7/site-packages/django/db/models/query.py", line 417, in get
    self.model._meta.object_name

Exception Type: DoesNotExist at /
Exception Value: Subscriber matching query does not exist.
```

**Comment by matt9j** [comment]
I'm able to work around this just by running populate.py in the short term, but we'll need to get the test data cleared out of the production app asap!
